version: "3.8"

services:
  mongodb:
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./app/:/app/:cached

volumes:
  mongodb_data:
